### ISSUE TITLE
Frequent connection errors

### ISSUE THREAD

**Issue by bbatsov** [voltrb/docs#23]
I often see [this error](https://www.dropbox.com/s/s3u43br1fg0r9h2/Screenshot%202015-04-04%2022.13.22.png?dl=0) while browsing the docs.

Can't imagine why we'd need a WebSocket for something like a documentation web site.

**Comment by ryanstout** [comment]
This is just the volt app dropping its connection. Voltframework is on an older version of volt. In the newer version it only creates socket connections when a subscription starts. Still, it's weird it would be dropping. Are you behind a proxy or anything weird?

**Comment by ryanstout** [comment]
@bbatsov any updates on this, closing for now.

**Comment by bbatsov** [comment]
> Are you behind a proxy or anything weird?

No, I'm not.

**Comment by ryanstout** [comment]
Are you still seeing this issue?

**Comment by bbatsov** [comment]
Yep, pretty much all the time.

**Comment by ryanstout** [comment]
@bbatsov strange. What is/browser?

**Comment by bbatsov** [comment]
Chrome Version 41.0.2272.118 (64-bit), running on OS X Yosemite.
