### ISSUE TITLE
model feedbak

### ISSUE THREAD

**Issue by rubydesign** [voltrb/docs#57]
Hi Ryan,
just reading the book and writing down what i think. If our timezones were more aligned i would chat.

First off all it's a very good effort. With a moving target i know the effort it takes to keep documentation half up do date, so none of this is criticism. Just a list, delete at will.
- start with the models chapter. everything depends on that. then view
- models overview is good, the model classes is a bit orphaned, just include it
- in the models classes page it's not clear what happens when you assign a hash (tried, turns to Info) and can one assign different classes or is that .info - Info convention enforced. (is no, tried)
- similar with that plural conversion, can one assign a random classed model to a plural. Yes
- how about instance variables in models ( don't know, hope they are transient)
- collections could easily be it's own chapter, then the order in models chapter would improve
- associations: how are they set up. And the eternal rails question: what is the difference between has_one and belongs_to.
- array model events is good. but i was missing similar functionality for model, some .on function, or other way to hook into the update mechanism.

So, just a newbies view.  Leave a comment if you want more, i know it always feels like a lot.

**Comment by ryanstout** [comment]
@dancinglightning this kind of feedback is super valuable.  More would always be appreciated.  Thanks

**Comment by dancinglightning** [comment]
ok, good. wasn't sure. Got a couple more and can do a full read after you have made changes.

- In chapter 3, the intro is brief. Drop the "read the source" and give a short overview of the chapters. or better still .. 
- hoist all 3.x chapters up as main chapters. if that becomes to many chapters, try to condense later
- the 3.4 rendering first half is an excellent intro into volt. It could be in 3.0 or even further up.
- 3.4's second half about computations and dependencies is an appendix (not relevant for 95% of the people)
- the component chapter 3.7 should come straight after the view (which should be after the model )
- 3.3 uses a model :page . Page as i understand is meant to me a model, but it is confusing. Page is after all a collection (Collections being models does not help the distinction), suggest another model name
- same chapter has the sentence "See the provided collections section for a list of the available collection models." i hope you can see how that would be confusing, collections, models, which is it now.
chapter 8 is thin, but the wiki page is great. Just import that into the book and delete it. Also point to it from the volt/readme
- the lib/gem issue is in 2 places, unite

**Comment by dancinglightning** [comment]
btw, might be nice to rename the repository, so when it is cloned you can know what it is. volt-docs , eg
