### ISSUE TITLE
Add MongoDb (or a general DB) information to Tutorials

### ISSUE THREAD

**Issue by dummey** [voltrb/docs#63]
I swear last time I looked through this stuff, there was a section about MongoDB and needing to have it up and running for the data syncing stuff to work. 

I know that moving forward, the idea is to be DB independent, but including enough information (in this case MongoDB installing and running) in the tutorial to get people up and running is important too.

**Comment by dummey** [comment]
I see it towards the end of 2.2 now. This originally came up when I ran `bundle exec volt server` and saw the red error:

```
[ERROR] Unable to connect to the database.  Volt will still run, but the message bus requires a database connection to setup connections between nodes, so the message bus has been disabled.  This means updates will not be propagated between instances (server, console, runners, etc...)
```

Maybe just a note in 2.1 that when starting without mongodb running, this error is expected would be good.

**Comment by ryanstout** [comment]
Added a better message to volt.
