### ISSUE TITLE
Pluralized Attributes in 2.1 could use additional hints about how to check for plurality

### ISSUE THREAD

**Issue by dummey** [voltrb/docs#64]
It's not clear what plural actually means until you dig into the code to find the magic classification hash. Not to also mention that it's confusing for made up words/compound words which often happens for variable names. 

An additional hint about plural being anything ending with an 's' except for this hard coded words would be nice. Or better yet, a code snippet which will allow a user to see whether their word is plural or not.

**Comment by ryanstout** [comment]
@dummey you can call .plural? or .singular? on a string.  I'm not sure how thats confusing.  The inflector is pretty good.  Closing for now, but feel free to add more docs for it.
